name: Run Repo-B CI Action
on: push
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run my action
      uses: mwinel/custom-action@main
